/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ealcaraz' at '12/15/16 9:22 AM' with Gradle 3.1
 *
 * @author ealcaraz, @date 12/15/16 9:22 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
